// Built-in fun topics for Extempore mode. Add, remove or edit freely.
export const BUILT_IN_TOPICS = [
  "Friendship",
  "My most embarrassing moment",
  "If animals could talk, the first thing they'd say",
  "The worst advice I've ever received",
  "A world without the internet",
  "Bull Balls, overrated or underrated?",
  "My villain origin story",
  "The perfect day off",
  "A superpower I'd secretly hate",
  "Why cats secretly rule the world",
  "The weirdest thing I've ever Googled",
  "If I became a billionaire tomorrow",
  "A conspiracy theory I'd start",
  "My dream road trip",
  "The best excuse for being late",
  "Something everyone pretends to like",
  "What I'd put in a time capsule",
  "My faviroute song (+why u like it)",
  "The most useless talent I have",
  "How gooing is effective and powerfull enough to change lives",
  "If I could swap lives with anyone for a day",
  "A rule I'd make if I were in charge of the world",
  "The dumbest thing I believed as a kid",
  "How I'd survive a zombie apocalypse",
  "A hill I will die on",
  "what do you think of the indian lesbian scene",
  "If my pet wrote a diary about me",
  "why Modi ji probably has 7inch +",
  "The worst gift I've ever received",
  "My biggest fear",
  "why paper.io beats skribbl",
  "What aliens would think of humans",
  "A hidden talent nobody knows I have",
  "Why Anushka is a bitch",
  "How Ravi kishan changed india forever",
  "If I had a personal theme song",
  "A day in the life of my future self",
  "if i were an indian spy in china",
  "What I'd do with one hour of invisibility",
  "why agastya is the funniest guy around",
  "if i could make a wish...",
  "if i were an animal....",
  "If I opened a restaurant",
  "Ravikant sir",
  "Write about agastya the feminist",
];
